### ISSUE TITLE
Feature Request: Cookie support in TestClient

### ISSUE THREAD

**Issue by taladar** [cloudwalk/axum-test-helper#18]
For applications which use a cookie based login mechanism it would be helpful if TestClient had built-in cookie support.

This should be relatively straightforward to implement, basically enable the cookie feature on the reqwest dependency and add a cookie_store(true) to the client builder.

If the additional dependencies are considered a problem this could probably also be enabled by a feature.

**Comment by renancloudwalk** [comment]
Merged, thanks!
