### ISSUE TITLE
Missing examples directory

### ISSUE THREAD

**Issue by peter-kehl** [cloudwalk/axum-test-helper#3]
Hi Renan,

[README.md](https://github.com/cloudwalk/axum-test-helper) reads "You can find examples like this in the example directory", which links to https://github.com/cloudwalk/axum-test-helper/tree/main/examples, which fails.

Did you mean any branch of https://github.com/tokio-rs/axum/blob/main/examples/testing, or any fork of https://github.com/tokio-rs/axum/blob/main/examples/testing?

**Comment by renancloudwalk** [comment]
Hi @peter-kehl  thanks for pointing it out, we solved this on #4 and it will be shipped on version 0.1.1
